### ISSUE TITLE
Error when launching main.py

### ISSUE THREAD

**Issue by beniroquai** [jhnnsrs/helloworld-standalone#1]
Hey @jhnnsrs, first of all: thanks for providing this code! 
But: It does not really like my machine it seems:

```
(chromatix) (base) Blynk:helloworld-standalone-master bene$ /Users/bene/mambaforge/envs/chromatix/bin/python /Users/bene/Downloads/helloworld-standalone-master/main.py
/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/_distutils_hack/__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Invalid hash
WARNING:fakts.grants.remote.demanders.cache:The cache  is no longer valid. Deleting it
ERROR:fakts.grants.remote.demanders.auto_save:Error! Could not retrieve code: Malformed request: 1 validation error for DeviceCodeStartRequest
manifest -> requirements
  value is not a valid dict (type=type_error.dict)
Traceback (most recent call last):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/auto_save.py", line 165, in ademand
    token = await self.demander.ademand(endpoint, request)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/device_code.py", line 174, in ademand
    code = await self.arequest_code(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/device_code.py", line 137, in arequest_code
    raise DeviceCodeError(
fakts.grants.remote.demanders.device_code.DeviceCodeError: Error! Could not retrieve code: Malformed request: 1 validation error for DeviceCodeStartRequest
manifest -> requirements
  value is not a valid dict (type=type_error.dict)
ERROR:fakts.fakts:Error! Could not retrieve code: Malformed request: 1 validation error for DeviceCodeStartRequest
manifest -> requirements
  value is not a valid dict (type=type_error.dict)
Traceback (most recent call last):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/fakts.py", line 126, in aget
    await self.aload(FaktsRequest(context=kwargs))
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/fakts.py", line 242, in aload
    self.loaded_fakts = await self.grant.aload(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/base.py", line 67, in aload
    token = await self.demander.ademand(endpoint, request)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/auto_save.py", line 179, in ademand
    raise e
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/auto_save.py", line 165, in ademand
    token = await self.demander.ademand(endpoint, request)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/device_code.py", line 174, in ademand
    code = await self.arequest_code(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/device_code.py", line 137, in arequest_code
    raise DeviceCodeError(
fakts.grants.remote.demanders.device_code.DeviceCodeError: Error! Could not retrieve code: Malformed request: 1 validation error for DeviceCodeStartRequest
manifest -> requirements
  value is not a valid dict (type=type_error.dict)
Traceback (most recent call last):
  File "/Users/bene/Downloads/helloworld-standalone-master/main.py", line 88, in <module>
    e.run()
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/arkitekt_next/apps/types.py", line 33, in run
    self.services["rekuest"].run()
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/rekuest.py", line 49, in run
    return unkoil(self.arun, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/koil/helpers.py", line 143, in unkoil
    x, newcontext = co_future.result()
                    ^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/koil/helpers.py", line 133, in passed_with_context
    x = await coro(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/rekuest.py", line 55, in arun
    await self.agent.aprovide()
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/agents/base.py", line 489, in aprovide
    await self.astart(instance_id=instance_id)
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/agents/base.py", line 387, in astart
    await self.aregister_definitions(instance_id=instance_id)
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/agents/base.py", line 321, in aregister_definitions
    x = await aensure_agent(
        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/api/schema.py", line 1581, in aensure_agent
    await aexecute(
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/funcs.py", line 12, in aexecute
    x = await rath.aquery(
        ^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/rath.py", line 94, in aquery
    async for data in self.link.aexecute(op):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/links/compose.py", line 119, in aexecute
    async for result in self._firstlink.aexecute(operation):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/links/parsing.py", line 52, in aexecute
    async for result in self.next.aexecute(operation, **kwargs):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/links/parsing.py", line 52, in aexecute
    async for result in self.next.aexecute(operation, **kwargs):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/links/auth.py", line 86, in aexecute
    token = await self.aload_token(operation)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/contrib/herre/links/auth.py", line 14, in aload_token
    return await herre.aget_token()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre/herre.py", line 116, in aget_token
    await self.arequest_from_grant(TokenRequest(context=kwargs))
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre/herre.py", line 157, in arequest_from_grant
    potential_token = await self.grant.afetch_token(request)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre/grants/oauth2/refresh.py", line 112, in afetch_token
    self._token = await self.grant.afetch_token(request)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre/fakts/grant.py", line 106, in afetch_token
    self._old_fakt = await self.fakts.aget(self.fakts_group)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/fakts.py", line 129, in aget
    raise e
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/fakts.py", line 126, in aget
    await self.aload(FaktsRequest(context=kwargs))
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/fakts.py", line 242, in aload
    self.loaded_fakts = await self.grant.aload(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/base.py", line 67, in aload
    token = await self.demander.ademand(endpoint, request)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/auto_save.py", line 179, in ademand
    raise e
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/auto_save.py", line 165, in ademand
    token = await self.demander.ademand(endpoint, request)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/device_code.py", line 174, in ademand
    code = await self.arequest_code(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/device_code.py", line 137, in arequest_code
    raise DeviceCodeError(
fakts.grants.remote.demanders.device_code.DeviceCodeError: Error! Could not retrieve code: Malformed request: 1 validation error for DeviceCodeStartRequest
manifest -> requirements
  value is not a valid dict (type=type_error.dict)
```

I've entered the URL (of my local computer). Arkitekt Server is running and I can connect via Orkestrator. I used the latest python version [all]
![Bildschirmfoto 2024-10-26 um 14 18 44](https://github.com/user-attachments/assets/7f063470-f67d-415c-9c8f-1027a898ff30)
. 

Does this look familiar? Do I need to provide a token somewhere?

**Comment by jhnnsrs** [comment]
Hi hi,

This is hopefully the last breaking change in arkitekt next and should be fixed in arkitekt-next > 0.8.19 with the lastest changes pull from the GitHub repos on the server side. Should be resolved if you update each server side repo (and restart with docker compose down, and docker compose up). Does that fix things ?

**Comment by beniroquai** [comment]
On Python after doing `docker compose up` I still get this:

```py
>mikro-next>=0.1.43->arkitekt-next[all,blok]) (2.2.2)
Downloading arkitekt_next-0.8.19-py3-none-any.whl (635 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 635.9/635.9 kB 5.2 MB/s eta 0:00:00
Installing collected packages: arkitekt-next
  Attempting uninstall: arkitekt-next
    Found existing installation: arkitekt-next 0.8.16
    Uninstalling arkitekt-next-0.8.16:
      Successfully uninstalled arkitekt-next-0.8.16
Successfully installed arkitekt-next-0.8.19
(chromatix) (base) Blynk:helloworld-standalone-master bene$ npm run start
(chromatix) (base) Blynk:helloworld-standalone-master bene$ /Users/bene/mambaforge/envs/chromatix/bin/python /Users/bene/Downloads/helloworld-standalone-master/main.py
/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/_distutils_hack/__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Invalid hash
WARNING:fakts.grants.remote.demanders.cache:The cache  is no longer valid. Deleting it
ERROR:fakts.grants.remote.demanders.auto_save:Error! Could not retrieve code: Malformed request: 1 validation error for DeviceCodeStartRequest
manifest -> requirements
  value is not a valid dict (type=type_error.dict)
Traceback (most recent call last):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/auto_save.py", line 165, in ademand
    token = await self.demander.ademand(endpoint, request)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/device_code.py", line 174, in ademand
    code = await self.arequest_code(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/device_code.py", line 137, in arequest_code
    raise DeviceCodeError(
fakts.grants.remote.demanders.device_code.DeviceCodeError: Error! Could not retrieve code: Malformed request: 1 validation error for DeviceCodeStartRequest
manifest -> requirements
  value is not a valid dict (type=type_error.dict)
ERROR:fakts.fakts:Error! Could not retrieve code: Malformed request: 1 validation error for DeviceCodeStartRequest
manifest -> requirements
  value is not a valid dict (type=type_error.dict)
Traceback (most recent call last):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/fakts.py", line 126, in aget
    await self.aload(FaktsRequest(context=kwargs))
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/fakts.py", line 242, in aload
    self.loaded_fakts = await self.grant.aload(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/base.py", line 67, in aload
    token = await self.demander.ademand(endpoint, request)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/auto_save.py", line 179, in ademand
    raise e
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/auto_save.py", line 165, in ademand
    token = await self.demander.ademand(endpoint, request)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/device_code.py", line 174, in ademand
    code = await self.arequest_code(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/device_code.py", line 137, in arequest_code
    raise DeviceCodeError(
fakts.grants.remote.demanders.device_code.DeviceCodeError: Error! Could not retrieve code: Malformed request: 1 validation error for DeviceCodeStartRequest
manifest -> requirements
  value is not a valid dict (type=type_error.dict)
Traceback (most recent call last):
  File "/Users/bene/Downloads/helloworld-standalone-master/main.py", line 88, in <module>
    e.run()
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/arkitekt_next/apps/types.py", line 33, in run
    self.services["rekuest"].run()
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/rekuest.py", line 49, in run
    return unkoil(self.arun, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/koil/helpers.py", line 143, in unkoil
    x, newcontext = co_future.result()
                    ^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/koil/helpers.py", line 133, in passed_with_context
    x = await coro(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/rekuest.py", line 55, in arun
    await self.agent.aprovide()
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/agents/base.py", line 489, in aprovide
    await self.astart(instance_id=instance_id)
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/agents/base.py", line 387, in astart
    await self.aregister_definitions(instance_id=instance_id)
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/agents/base.py", line 321, in aregister_definitions
    x = await aensure_agent(
        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/api/schema.py", line 1581, in aensure_agent
    await aexecute(
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/funcs.py", line 12, in aexecute
    x = await rath.aquery(
        ^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/rath.py", line 94, in aquery
    async for data in self.link.aexecute(op):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/links/compose.py", line 119, in aexecute
    async for result in self._firstlink.aexecute(operation):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/links/parsing.py", line 52, in aexecute
    async for result in self.next.aexecute(operation, **kwargs):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/links/parsing.py", line 52, in aexecute
    async for result in self.next.aexecute(operation, **kwargs):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/links/auth.py", line 86, in aexecute
    token = await self.aload_token(operation)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/contrib/herre/links/auth.py", line 14, in aload_token
    return await herre.aget_token()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre/herre.py", line 116, in aget_token
    await self.arequest_from_grant(TokenRequest(context=kwargs))
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre/herre.py", line 157, in arequest_from_grant
    potential_token = await self.grant.afetch_token(request)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre/grants/oauth2/refresh.py", line 112, in afetch_token
    self._token = await self.grant.afetch_token(request)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre/fakts/grant.py", line 106, in afetch_token
    self._old_fakt = await self.fakts.aget(self.fakts_group)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/fakts.py", line 129, in aget
    raise e
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/fakts.py", line 126, in aget
    await self.aload(FaktsRequest(context=kwargs))
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/fakts.py", line 242, in aload
    self.loaded_fakts = await self.grant.aload(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/base.py", line 67, in aload
    token = await self.demander.ademand(endpoint, request)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/auto_save.py", line 179, in ademand
    raise e
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/auto_save.py", line 165, in ademand
    token = await self.demander.ademand(endpoint, request)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/device_code.py", line 174, in ademand
    code = await self.arequest_code(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts/grants/remote/demanders/device_code.py", line 137, in arequest_code
    raise DeviceCodeError(
fakts.grants.remote.demanders.device_code.DeviceCodeError: Error! Could not retrieve code: Malformed request: 1 validation error for DeviceCodeStartRequest
manifest -> requirements
  value is not a valid dict (type=type_error.dict)
```

**Comment by beniroquai** [comment]
Is there a way to check the version of arkitekt-next in docker?

That's what my console says:
<img width="1142" alt="image" src="https://github.com/user-attachments/assets/28319b2a-27fe-4ca8-9db7-a854efa1a2d7">

**Comment by jhnnsrs** [comment]
Soon there will be once I build the containers with versions in mind they will have something like: "jhnnsrs/rekuest_next:0.0.1" but that's next week buisness

For now the images are build directly from the associated GitHub repos (if you created the build with the --dev flags enabled, outlined https://arkitekt.live/docs/roadmap/installation#installation-of-the-server ) which also have the dockerfiles inside. You therefore need to pull changes there ;)

Hope that helps.

**Comment by beniroquai** [comment]
So for updating the server files I would need to do 
```
blok build arkitekt $PATH_TO_PROJECT --fluss-dev=True --rekuest-dev=True --lok-dev=True --mikro-dev=True --orkestrator-dev=True --kabinet-dev=True --postgres-dev=True
```
in a fresh folder? I think I understood you wrong here..or? The docker comopse file has everything inside already, no? I mean, it will pull the latest images from the registry, no?

**Comment by jhnnsrs** [comment]
No. That should have been how you installed it. (And looking at the
container names I guess that is the case). A simple git pull in each mount
folder should do the trick ;)

**Comment by beniroquai** [comment]
I want a script for this 
```
for dir in */; do
  (cd "$dir" && git pull)
done
```

**Comment by beniroquai** [comment]
Insane! Kaum macht mans richtig, schon funktionierts

```py
(chromatix) (base) Blynk:helloworld-standalone-master bene$ /Users/bene/mambaforge/envs/chromatix/bin/python /Users/bene/Downloads/helloworld-standalone-master/main.py
/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/_distutils_hack/__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Invalid hash
WARNING:fakts.grants.remote.demanders.cache:The cache  is no longer valid. Deleting it
╭─────────────────────────────── Device Code Grant ────────────────────────────────╮
│                                                                                  │
│     Please visit the following URL:                                              │
│     http://192.168.2.191/lok/f/configure/?device_code=930ef51f&grant=device_code │
│     or go to this URL:                                                           │
│     http://192.168.2.191/lok/f/device                                            │
│     and enter the code:                                                          │
│     930ef51f                                                                     │
│                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────╯
Invalid hash
WARNING:fakts.grants.remote.demanders.cache:The cache  is no longer valid. Deleting it
```
