### ISSUE TITLE
Cannot find endpoint? 

### ISSUE THREAD

**Issue by beniroquai** [jhnnsrs/helloworld-standalone#3]
After updating all docker images in mount and doing docker compose down/up, I get this: (python client later)

```py
arkitekt-next-internal_docker-1  | DiscoveryError: Error! We could not retrieve the endpoint. 
arkitekt-next-internal_docker-1  | http://caddy:80/.well-known/fakts 
arkitekt-next-internal_docker-1  | 
arkitekt-next-internal_docker-1  | The above exception was the direct cause of the following exception:
arkitekt-next-internal_docker-1  | 
arkitekt-next-internal_docker-1  | ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │ /usr/local/lib/python3.11/site-packages/arkitekt_next/cli/commands/run/prod. │
arkitekt-next-internal_docker-1  | │ py:63 in prod                                                                │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │   60 │   console.print(panel)                                                │
arkitekt-next-internal_docker-1  | │   61 │                                                                       │
arkitekt-next-internal_docker-1  | │   62 │   try:                                                                │
arkitekt-next-internal_docker-1  | │ ❱ 63 │   │   asyncio.run(run_app(app))                                       │
arkitekt-next-internal_docker-1  | │   64 │   except Exception as e:                                              │
arkitekt-next-internal_docker-1  | │   65 │   │   console.print_exception()                                       │
arkitekt-next-internal_docker-1  | │   66 │   │   sys.exit(1)                                                     │
arkitekt-next-internal_docker-1  | │ /usr/local/lib/python3.11/asyncio/runners.py:190 in run                      │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │   187 │   │   │   "asyncio.run() cannot be called from a running event loop" │
arkitekt-next-internal_docker-1  | │   188 │                                                                      │
arkitekt-next-internal_docker-1  | │   189 │   with Runner(debug=debug) as runner:                                │
arkitekt-next-internal_docker-1  | │ ❱ 190 │   │   return runner.run(main)                                        │
arkitekt-next-internal_docker-1  | │   191                                                                        │
arkitekt-next-internal_docker-1  | │   192                                                                        │
arkitekt-next-internal_docker-1  | │   193 def _cancel_all_tasks(loop):                                           │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │ /usr/local/lib/python3.11/asyncio/runners.py:118 in run                      │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │   115 │   │                                                                  │
arkitekt-next-internal_docker-1  | │   116 │   │   self._interrupt_count = 0                                      │
arkitekt-next-internal_docker-1  | │   117 │   │   try:                                                           │
arkitekt-next-internal_docker-1  | │ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                 │
arkitekt-next-internal_docker-1  | │   119 │   │   except exceptions.CancelledError:                              │
arkitekt-next-internal_docker-1  | │   120 │   │   │   if self._interrupt_count > 0:                              │
arkitekt-next-internal_docker-1  | │   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)             │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │ /usr/local/lib/python3.11/asyncio/base_events.py:653 in run_until_complete   │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │    650 │   │   if not future.done():                                         │
arkitekt-next-internal_docker-1  | │    651 │   │   │   raise RuntimeError('Event loop stopped before Future comp │
arkitekt-next-internal_docker-1  | │    652 │   │                                                                 │
arkitekt-next-internal_docker-1  | │ ❱  653 │   │   return future.result()                                        │
arkitekt-next-internal_docker-1  | │    654 │                                                                     │
arkitekt-next-internal_docker-1  | │    655 │   def stop(self):                                                   │
arkitekt-next-internal_docker-1  | │    656 │   │   """Stop running the event loop.                               │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │ /usr/local/lib/python3.11/site-packages/arkitekt_next/cli/commands/run/prod. │
arkitekt-next-internal_docker-1  | │ py:15 in run_app                                                             │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │   12 │   rekuest = app.services.get("rekuest")                               │
arkitekt-next-internal_docker-1  | │   13 │                                                                       │
arkitekt-next-internal_docker-1  | │   14 │   async with app:                                                     │
arkitekt-next-internal_docker-1  | │ ❱ 15 │   │   await rekuest.run()                                             │
arkitekt-next-internal_docker-1  | │   16                                                                         │
arkitekt-next-internal_docker-1  | │   17                                                                         │
arkitekt-next-internal_docker-1  | │   18 @click.command("prod")                                                  │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │ /usr/local/lib/python3.11/site-packages/rekuest_next/rekuest.py:55 in arun   │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │   52 │   │   """                                                             │
arkitekt-next-internal_docker-1  | │   53 │   │   Run the application.                                            │
arkitekt-next-internal_docker-1  | │   54 │   │   """                                                             │
arkitekt-next-internal_docker-1  | │ ❱ 55 │   │   await self.agent.aprovide()                                     │
arkitekt-next-internal_docker-1  | │   56 │                                                                       │
arkitekt-next-internal_docker-1  | │   57 │   def _repr_html_inline_(self):                                       │
arkitekt-next-internal_docker-1  | │   58 │   │   return f"<table><tr><td>rath</td><td>{self.rath._repr_html_inli │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │ /usr/local/lib/python3.11/site-packages/rekuest_next/agents/base.py:464 in   │
arkitekt-next-internal_docker-1  | │ aprovide                                                                     │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │   461 │   │   logger.info(                                                   │
arkitekt-next-internal_docker-1  | │   462 │   │   │   f"Launching provisioning task. We are running {self.transp │
arkitekt-next-internal_docker-1  | │   463 │   │   )                                                              │
arkitekt-next-internal_docker-1  | │ ❱ 464 │   │   await self.astart(instance_id=instance_id)                     │
arkitekt-next-internal_docker-1  | │   465 │   │   logger.info("Starting to listen for requests")                 │
arkitekt-next-internal_docker-1  | │   466 │   │   await self.aloop()                                             │
arkitekt-next-internal_docker-1  | │   467                                                                        │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │ /usr/local/lib/python3.11/site-packages/rekuest_next/agents/base.py:431 in   │
arkitekt-next-internal_docker-1  | │ astart                                                                       │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │   428 │   │   │   await self.process(await done.pop())                       │
arkitekt-next-internal_docker-1  | │   429 │                                                                      │
arkitekt-next-internal_docker-1  | │   430 │   async def astart(self, instance_id: Optional[str] = None):         │
arkitekt-next-internal_docker-1  | │ ❱ 431 │   │   self._context = await self.hook_registry.arun_startup(self.ins │
arkitekt-next-internal_docker-1  | │   432 │   │   await self.hook_registry.arun_background(self._context)        │
arkitekt-next-internal_docker-1  | │   433 │   │                                                                  │
arkitekt-next-internal_docker-1  | │   434 │   │   await self.aregister_definitions(instance_id=instance_id)      │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │ /usr/local/lib/python3.11/site-packages/rekuest_next/agents/hooks.py:49 in   │
arkitekt-next-internal_docker-1  | │ arun_startup                                                                 │
arkitekt-next-internal_docker-1  | │                                                                              │
arkitekt-next-internal_docker-1  | │    46 │   │   │   │   if answer is not None:                                 │
arkitekt-next-internal_docker-1  | │    47 │   │   │   │   │   context.update(answer)                             │
arkitekt-next-internal_docker-1  | │    48 │   │   │   except Exception as e:                                     │
arkitekt-next-internal_docker-1  | │ ❱  49 │   │   │   │   raise StartupHookError(f"Startup hook {key} failed") f │
arkitekt-next-internal_docker-1  | │    50 │   │   return context                                                 │
arkitekt-next-internal_docker-1  | │    51 │                                                                      │
arkitekt-next-internal_docker-1  | │    52 │   async def arun_background(self, context: Dict[str, Any]):          │
arkitekt-next-internal_docker-1  | ╰──────────────────────────────────────────────────────────────────────────────╯
arkitekt-next-internal_docker-1  | StartupHookError: Startup hook on_startup failed
arkitekt-next-internal_docker-1  | 
arkitekt-next-internal_docker-1 exited with code 1
arkitekt-next-caddy-1            | {"level":"error","ts":1730149575.988474,"logger":"http.log.error","msg":"dial tcp 172.18.0.9:80: connect: connection refused","request":{"remote_ip":"172.18.0.1","remote_port":"42618","client_ip":"172.18.0.1","proto":"HTTP/1.1","method":"GET","host":"127.0.0.1","uri":"/.well-known/fakts","headers":{"User-Agent":["Fakts/0.1"],"Accept":["application/json"],"Accept-Encoding":["gzip, deflate"]}},"duration":0.004467542,"status":502,"err_id":"p26ajwvdw","err_trace":"reverseproxy.statusError (reverseproxy.go:1269)"}
arkitekt-next-db-1               | 2024-10-28 21:08:07.959 UTC [236] LOG:  checkpoint starting: time
arkitekt-next-db-1               | 2024-10-28 21:09:20.418 UTC [236] LOG:  checkpoint complete: wrote 705 buffers (4.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=72.395 s, sync=0.040 s, total=72.462 s; sync files=553, longest=0.004 s, average=0.001 s; distance=3936 kB, estimate=3936 kB; lsn=0/36787D8, redo lsn=0/36787A0




arkitekt-next-caddy-1            | {"level":"error","ts":1730150769.6115808,"logger":"http.log.error","msg":"dial tcp 172.18.0.9:80: connect: connection refused","request":{"remote_ip":"172.18.0.1","remote_port":"57718","client_ip":"172.18.0.1","proto":"HTTP/1.1","method":"GET","host":"127.0.0.1","uri":"/.well-known/fakts","headers":{"User-Agent":["Fakts/0.1"],"Accept":["application/json"],"Accept-Encoding":["gzip, deflate"]}},"duration":0.009042042,"status":502,"err_id":"q1vqbd8c4","err_trace":"reverseproxy.statusError (reverseproxy.go:1269)"}
arkitekt-next-caddy-1            | {"level":"error","ts":1730150888.0341237,"logger":"http.log.error","msg":"dial tcp 172.18.0.9:80: connect: connection refused","request":{"remote_ip":"172.18.0.1","remote_port":"50776","client_ip":"172.18.0.1","proto":"HTTP/2.0","method":"GET","host":"localhost","uri":"/.well-known/fakts","headers":{"Accept-Language":["de"],"Priority":["u=1, i"],"Sec-Ch-Ua":["\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\""],"Accept":["*/*"],"Sec-Fetch-Mode":["cors"],"Accept-Encoding":["gzip, deflate, br"],"Sec-Fetch-Dest":["empty"],"Sec-Ch-Ua-Mobile":["?0"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) orkestrator-next/1.0.6 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Sec-Fetch-Site":["cross-site"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"localhost"}},"duration":0.004848625,"status":502,"err_id":"2xq9hfpz8","err_trace":"reverseproxy.statusError (reverseproxy.go:1269)"}
arkitekt-next-caddy-1            | {"level":"error","ts":1730150888.0522661,"logger":"http.log.error","msg":"dial tcp 172.18.0.9:80: connect: connection refused","request":{"remote_ip":"172.18.0.1","remote_port":"50776","client_ip":"172.18.0.1","proto":"HTTP/2.0","method":"GET","host":"localhost","uri":"/.well-known/fakts","headers":{"Priority":["u=1, i"],"Sec-Ch-Ua":["\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\""],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) orkestrator-next/1.0.6 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Sec-Fetch-Mode":["cors"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["de"],"Sec-Ch-Ua-Mobile":["?0"],"Accept":["*/*"],"Sec-Fetch-Site":["cross-site"],"Sec-Fetch-Dest":["empty"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"localhost"}},"duration":0.008658459,"status":502,"err_id":"tvb3pfw2h","err_trace":"reverseproxy.statusError (reverseproxy.go:1269)"}
```

The python file fails to connect:
```py
/Users/bene/mambaforge/envs/chromatix/bin/python /Users/bene/Downloads/helloworld-standalone-master/main.py

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(chromatix) (base) Blynk:helloworld-standalone-master bene$ /Users/bene/mambaforge/envs/chromatix/bin/python /Users/bene/Downloads/helloworld-standalone-master/main.py
/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/_distutils_hack/__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
ERROR:fakts_next.cache.file:Could not load cache file: 2 validation errors for CacheFile
config
  Field required [type=missing, input_value={'hash': 'cb5f5bd7cb76195...59e-9d49-faed130be5d0'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
created
  Field required [type=missing, input_value={'hash': 'cb5f5bd7cb76195...59e-9d49-faed130be5d0'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing. Ignoring it
ERROR:fakts_next.grants.remote.discovery.utils:Could not retrieve on the endpoint: 502
ERROR:fakts_next.fakts:Could not discover endpoint: Could not connect via any protocol: 
- https://127.0.0.1/
  Cannot connect to host 127.0.0.1:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
- http://127.0.0.1/
  Error! We could not retrieve the endpoint. http://127.0.0.1/.well-known/fakts 
Traceback (most recent call last):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/grants/remote/base.py", line 70, in aload
    endpoint = await self.discovery.adiscover()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/grants/remote/discovery/well_known.py", line 69, in adiscover
    return await discover_url(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/grants/remote/discovery/utils.py", line 126, in discover_url
    raise DiscoveryError(f"Could not connect via any protocol: \n{errors_string}")
fakts_next.grants.remote.errors.DiscoveryError: Could not connect via any protocol: 
- https://127.0.0.1/
  Cannot connect to host 127.0.0.1:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
- http://127.0.0.1/
  Error! We could not retrieve the endpoint. http://127.0.0.1/.well-known/fakts 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/fakts.py", line 266, in aload
    self.loaded_fakts = await self.grant.aload()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/grants/remote/base.py", line 72, in aload
    raise RemoteGrantError(f"Could not discover endpoint: {e}") from e
fakts_next.grants.remote.base.RemoteGrantError: Could not discover endpoint: Could not connect via any protocol: 
- https://127.0.0.1/
  Cannot connect to host 127.0.0.1:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
- http://127.0.0.1/
  Error! We could not retrieve the endpoint. http://127.0.0.1/.well-known/fakts 
ERROR:fakts_next.fakts:Could not discover endpoint: Could not connect via any protocol: 
- https://127.0.0.1/
  Cannot connect to host 127.0.0.1:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
- http://127.0.0.1/
  Error! We could not retrieve the endpoint. http://127.0.0.1/.well-known/fakts 
Traceback (most recent call last):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/grants/remote/base.py", line 70, in aload
    endpoint = await self.discovery.adiscover()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/grants/remote/discovery/well_known.py", line 69, in adiscover
    return await discover_url(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/grants/remote/discovery/utils.py", line 126, in discover_url
    raise DiscoveryError(f"Could not connect via any protocol: \n{errors_string}")
fakts_next.grants.remote.errors.DiscoveryError: Could not connect via any protocol: 
- https://127.0.0.1/
  Cannot connect to host 127.0.0.1:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
- http://127.0.0.1/
  Error! We could not retrieve the endpoint. http://127.0.0.1/.well-known/fakts 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/fakts.py", line 128, in aget
    await self.aload()
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/fakts.py", line 270, in aload
    raise e
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/fakts.py", line 266, in aload
    self.loaded_fakts = await self.grant.aload()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/grants/remote/base.py", line 72, in aload
    raise RemoteGrantError(f"Could not discover endpoint: {e}") from e
fakts_next.grants.remote.base.RemoteGrantError: Could not discover endpoint: Could not connect via any protocol: 
- https://127.0.0.1/
  Cannot connect to host 127.0.0.1:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
- http://127.0.0.1/
  Error! We could not retrieve the endpoint. http://127.0.0.1/.well-known/fakts 
Traceback (most recent call last):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/grants/remote/base.py", line 70, in aload
    endpoint = await self.discovery.adiscover()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/grants/remote/discovery/well_known.py", line 69, in adiscover
    return await discover_url(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/grants/remote/discovery/utils.py", line 126, in discover_url
    raise DiscoveryError(f"Could not connect via any protocol: \n{errors_string}")
fakts_next.grants.remote.errors.DiscoveryError: Could not connect via any protocol: 
- https://127.0.0.1/
  Cannot connect to host 127.0.0.1:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
- http://127.0.0.1/
  Error! We could not retrieve the endpoint. http://127.0.0.1/.well-known/fakts 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bene/Downloads/helloworld-standalone-master/main.py", line 88, in <module>
    e.run()
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/arkitekt_next/apps/types.py", line 33, in run
    self.services["rekuest"].run()
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/rekuest.py", line 49, in run
    return unkoil(self.arun, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/koil/helpers.py", line 143, in unkoil
    x, newcontext = co_future.result()
                    ^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/koil/helpers.py", line 133, in passed_with_context
    x = await coro(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/rekuest.py", line 55, in arun
    await self.agent.aprovide()
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/agents/base.py", line 493, in aprovide
    await self.astart(instance_id=instance_id)
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/agents/base.py", line 391, in astart
    await self.aregister_definitions(instance_id=instance_id)
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/agents/base.py", line 325, in aregister_definitions
    x = await aensure_agent(
        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/api/schema.py", line 1581, in aensure_agent
    await aexecute(
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rekuest_next/funcs.py", line 12, in aexecute
    x = await rath.aquery(
        ^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/rath.py", line 94, in aquery
    async for data in self.link.aexecute(op):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/links/compose.py", line 119, in aexecute
    async for result in self._firstlink.aexecute(operation):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/links/parsing.py", line 52, in aexecute
    async for result in self.next.aexecute(operation, **kwargs):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/links/parsing.py", line 52, in aexecute
    async for result in self.next.aexecute(operation, **kwargs):
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/rath/links/auth.py", line 86, in aexecute
    token = await self.aload_token(operation)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre_next/contrib/rath/auth_link.py", line 14, in aload_token
    return await herre.aget_token()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre_next/herre.py", line 116, in aget_token
    await self.arequest_from_grant(TokenRequest(context=kwargs))
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre_next/herre.py", line 157, in arequest_from_grant
    potential_token = await self.grant.afetch_token(request)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre_next/grants/oauth2/refresh.py", line 112, in afetch_token
    self._token = await self.grant.afetch_token(request)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/herre_next/fakts/grant.py", line 106, in afetch_token
    self._old_fakt = await self.fakts.aget(self.fakts_group)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/fakts.py", line 131, in aget
    raise e
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/fakts.py", line 128, in aget
    await self.aload()
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/fakts.py", line 270, in aload
    raise e
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/fakts.py", line 266, in aload
    self.loaded_fakts = await self.grant.aload()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/chromatix/lib/python3.11/site-packages/fakts_next/grants/remote/base.py", line 72, in aload
    raise RemoteGrantError(f"Could not discover endpoint: {e}") from e
fakts_next.grants.remote.base.RemoteGrantError: Could not discover endpoint: Could not connect via any protocol: 
- https://127.0.0.1/
  Cannot connect to host 127.0.0.1:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
- http://127.0.0.1/
  Error! We could not retrieve the endpoint. http://127.0.0.1/.well-known/fakts 
(chromatix) (base) Blynk:helloworld-standalone-master bene$ 
```

Any idea what'S going on?

**Comment by jhnnsrs** [comment]
Looks like the lok-server (which sets up the configuration for the app) is
not responding. Could you check the logs of that 'docker compose logs lok' ?

**Comment by beniroquai** [comment]
Here comes the lok-log. I'm in a hotel with a funky network I guess. But should not be an issue for localhost, or?
[lok-log.txt](https://github.com/user-attachments/files/17552112/lok-log.txt)

**Comment by beniroquai** [comment]
Yup. The network was the enemy. But that's strange. Cellphone wifi hotspot works.

**Comment by jhnnsrs** [comment]
Hmm that's weird. That means that postgres was not reachable from Lok after startup. Could be that it's too slow? How's performance right now? Could you also check if all images are arm64?

**Comment by beniroquai** [comment]
Seems like all images are ARM-based now? 

![Bildschirmfoto 2024-10-29 um 13 58 01](https://github.com/user-attachments/assets/2db9db23-d5c5-4e0b-a2b3-046269a28eaa)

Haven't checked performance yet. Will do so, now.

**Comment by jhnnsrs** [comment]
> Here comes the lok-log. I'm in a hotel with a funky network I guess. But should not be an issue for localhost, or? [lok-log.txt](https://github.com/user-attachments/files/17552112/lok-log.txt)

Actually the problem was probably not the network but lok server not running database migrations because the postgresdb was not up yet. fixed the missing "wait_for_database" startup routine in lok ;) Should now be resolved
